{"uuid": "fb6f64d4-1a90-45ef-a7dd-008c86988149", "children": ["bd007100-12a4-4e41-a576-a538480e176e"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "UnboundLocalError: cannot access local variable 'driver' where it is not associated with a value\n", "trace": "  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 877, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\User\\Documents\\Diplom_Sergey_Markov_7\\Diplom_3\\conftest.py\", line 14, in driver\n    driver.get(data.Urls.STELLAR_BURGERS)\n    ^^^^^^\n"}, "start": 1717742662032, "stop": 1717742662032}], "start": 1717742662032, "stop": 1717742662075}